FROM gcr.io/kaggle-images/python:latest
RUN mkdir -p /kaggle/working
# RUN mkdir -p /kaggle/working && \
    # conda install -y -c conda-forge mlflow

# # For more information, please refer to https://aka.ms/vscode-docker-python
# FROM gcr.io/kaggle-images/python:v56

# WORKDIR /code

# COPY ./requirements.txt ./

# # Install pip requirements
# # set --upgrade flag to upgrade pip first and set --no-cache-dir flag to avoid caching the index locally
# RUN pip install -U pip && \
#     pip install fastprogress japanize-matplotlib