version: '3.4'

services:
  programming:
    image: programming
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 kaggle/student_performance_from_game_play/predict-student-performance-from-game-play/jo_wilder/__init__.py "]
    ports:
      - 5678:5678
